Clase6/MundialClubes/MundialClubes.Web/Models/ErrorViewModel.cs
namespace MundialClubes.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Clase6/MundialClubes/MundialClubes.Web/Controllers/JugadorEstrellaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MundialClubes.Entidades.EF;
using MundialClubes.Logica;

namespace MundialClubes.Web.Controllers
{
    public class JugadorEstrellaController : Controller
    {
        private readonly IJugadorEstrellaLogica _jugadorEstrellaLogica;
        private readonly IClubLogica _clubLogica;

        public JugadorEstrellaController(IJugadorEstrellaLogica jugadorEstrellaLogica, IClubLogica clubLogica)
        {
            _jugadorEstrellaLogica = jugadorEstrellaLogica;
            _clubLogica = clubLogica;
        }

        public IActionResult Lista()
        {
            return View(_jugadorEstrellaLogica.ObtenerTodosLosJugadores());
        }

        public IActionResult Agregar()
        {
            CargarViewBagClubs();
            return View();
        }

        private void CargarViewBagClubs(int? idClub = null)
        {
            List<Club> clubs = _clubLogica.ObtenerTodosLosClubs();
            var clubsItems = new SelectList(clubs.ToList(), "IdClub", "Nombre", idClub);
            ViewBag.Clubs = clubsItems;
        }

        [HttpPost]
        public IActionResult Agregar(JugadorEstrella jugador, int? IdClub, string? NuevoClub)
        {
            if (ModelState.IsValid)
            {
                // Verificar si se ingresó un nuevo club
                AsignarClubAJugador(jugador, IdClub, NuevoClub);
                _jugadorEstrellaLogica.AgregarJugador(jugador);
                return Redirect("Lista");
            }
            CargarViewBagClubs();
            return View(jugador);
        }

        private void AsignarClubAJugador(JugadorEstrella jugadorEstrella, int? IdClub, string? NuevoClub)
        {
            if (!string.IsNullOrEmpty(NuevoClub))
            {
                jugadorEstrella.Club = new Club
                {
                    Nombre = NuevoClub,
                    IdJugadorEstrella = jugadorEstrella.IdJugadorEstrella 
                };
            }
            else if (IdClub != null)
            {
                var club = _clubLogica.ObtenerPorId(IdClub);
                jugadorEstrella.Club = club;
            }
            else
            {
                jugadorEstrella.Club = null;
            }
        }

        public IActionResult Editar(int id)
        {
            var jugador = _jugadorEstrellaLogica.ObtenerJugadorPorId(id);
            if (jugador == null)
            {
                return NotFound();
            }
            return View(jugador);
        }

        [HttpPost]
        public IActionResult Editar(JugadorEstrella jugador)
        {
            if (ModelState.IsValid)
            {
                _jugadorEstrellaLogica.Actualizar(jugador);
                return RedirectToAction("Lista");
            }
            return View(jugador);
        }

        public IActionResult Eliminar(int id)
        {  
            _jugadorEstrellaLogica.EliminarJugador(id);
            return RedirectToAction("Lista"); 
        }

    }
}

Clase6/MundialClubes/MundialClubes.Web/Views/JugadorEstrella/Agregar.cshtml
@model MundialClubes.Entidades.EF.JugadorEstrella

@{
    ViewData["Title"] = "Agregar Jugador Estrella";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Agregar Jugador Estrella</h1>
<form asp-action="Agregar" method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Edad"></label>
        <input asp-for="Edad" class="form-control" type="number" />
        <span asp-validation-for="Edad" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="FotoUrl"></label>
        <input asp-for="FotoUrl" class="form-control" />
        <span asp-validation-for="FotoUrl" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Descripcion"></label>
        <textarea asp-for="Descripcion" class="form-control"></textarea>
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label>Club: </label>
        @* dropdown club *@
        <select name="IdClub" class="form-select" asp-items="ViewBag.Clubs">
            <option value="">-- Sin club --</option>
        </select>
        @* input para nuevo club *@
        <input type="text" name="NuevoClub" class="form-control" placeholder="Nuevo Club (opcional)" />
    </div>


    <div class="mb-3">
    <button type="submit" class="btn btn-primary">Agregar</button>

    <a href="/Lista" class="btn btn-secondary">Volver a la lista</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Clase6/MundialClubes/MundialClubes.Web/Views/JugadorEstrella/Editar.cshtml
@model MundialClubes.Entidades.EF.JugadorEstrella   

@{
    ViewData["Title"] = "Editar Jugador Estrella";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar Jugador Estrella</h1>
<form asp-action="Editar" method="post" enctype="multipart/form-data">
   <input type="hidden" asp-for="IdJugadorEstrella"/>
    <div class="mb-3">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Edad"></label>
        <input asp-for="Edad" class="form-control" type="number" />
        <span asp-validation-for="Edad" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="FotoUrl">Foto</label>
        <input asp-for="FotoUrl" class="form-control" />
        <span asp-validation-for="FotoUrl" class="text-danger"></span>
        <div class="mt-2">
            <img src="@Model.FotoUrl" alt="@Model.Nombre" style="height: 100px;"/>
        </div>

    </div>
    <div class="mb-3">
        <label asp-for="Descripcion"></label>
        <textarea asp-for="Descripcion" class="form-control"></textarea>
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>

     @* Combo de clubs *@
    <div class="mb-3">
        <label>Club: </label>
        <select name="IdClub" class="form-select" asp-items="ViewBag.Clubs">
            <option value="">-- Sin club --</option>
        </select>
        @* Input para nuevo club *@
        <input type="text" name="NuevoClub" class="form-control" placeholder="Nuevo Club (opcional)" />
    </div>

    <div class="mb-3">
    <button type="submit" class="btn btn-primary">Guardar</button>

    <a asp-action="Lista" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

Clase6/MundialClubes/MundialClubes.Web/Views/JugadorEstrella/Lista.cshtml
@model List<MundialClubes.Entidades.EF.JugadorEstrella>

    @{
    ViewData["Title"] = "Lista de Jugadores Estrella";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Lista de Jugadores Estrella</h1>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Foto</th>
                <th>Descripcion</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var jugador in Model)
            {
                <tr class="text-center align-middle">
                <td>
                    <a href="/JugadorEstrella/Editar/@jugador.IdJugadorEstrella" class="text-decoration-none fw-semibold">
                        @jugador.Nombre
                    </a>
                </td>
                <td>
                    @if (!string.IsNullOrWhiteSpace(jugador.FotoUrl))
                    {
                        <img src="@jugador.FotoUrl" style="height:120px; width:100px; object-fit:cover;" alt="@jugador.Nombre" />
                    }
                </td>
                <td>@jugador.Descripcion</td>
                    <td><a href="/JugadorEstrella/Eliminar/@jugador.IdJugadorEstrella">Eliminar</a></td>
                </tr>
            }
    </tbody>
</table>

Clase6/MundialClubes/MundialClubes.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MundialClubes.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MundialClubes.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="JugadorEstrella" asp-action="Lista">MundialClubes.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JugadorEstrella" asp-action="Lista">Jugadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JugadorEstrella" asp-action="Agregar">Agregar Jugador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MundialClubes.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>