Clase3/Clase.MVC.WebApp/Models/ErrorViewModel.cs
namespace Clase.MVC.WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Clase3/Clase.MVC.WebApp/Controllers/AnimalesController.cs
using Clase3.MVC.Servicio;
using Microsoft.AspNetCore.Mvc;

namespace Clase.MVC.WebApp.Controllers
{
    public class AnimalesController : Controller
    {
        private IAnimalServicio _animalServicio;

        public AnimalesController(IAnimalServicio animalServicio)
        {
            _animalServicio = animalServicio;
        }
        public IActionResult Index()
        {
            return View(_animalServicio.ObtenerAnimales());
        }

        [HttpGet]
        public IActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Agregar(string descripcion, decimal precio)
        {
            _animalServicio.AgregarAnimal(new Clase3.MVC.Entidades.Animal { Descripcion =  descripcion, Precio= precio });
            return RedirectToAction("Index");
        }
    }
}

Clase3/Clase.MVC.WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Clase.MVC.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace Clase.MVC.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Clase3/Clase.MVC.WebApp/Controllers/api/ValuesController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Clase.MVC.WebApp.Controllers.api
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        // GET: api/<ValuesController>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<ValuesController>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<ValuesController>
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/<ValuesController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/<ValuesController>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

Clase3/Clase.MVC.WebApp/Views/Animales/Agregar.cshtml
@model Clase3.MVC.Entidades.Animal
@{
}

<form method="post">
	<div class="form-group">
		<label asp-for="Descripcion" class="control-label"> </label>
		<input asp-for="Descripcion" class="form-control"/>
	</div>

	<div class="form-group">
		<label asp-for="Precio" class="control-label"> </label>
		<input asp-for="Precio" class="form-control" />
	</div>

	<button type="submit" class="btn btn-primary"> Guardar</button>

</form>

Clase3/Clase.MVC.WebApp/Views/Animales/Index.cshtml
@model List<Clase3.MVC.Entidades.Animal>
@{
}

<h1>Lista de Animales </h1>

<Table class="table">
	<thead>
		<th>Descripcion</th>
		<th>Precio</th>
		<th>Imagen</th>
	</thead>
	<tbody>
		@foreach (var animal in Model)
		{
			<tr>
				<td>@animal.Descripcion</td>
				<td>@animal.Precio</td>
				<td><img src="@animal.Imagen" alt="Imagen de @animal.Descripcion" style="width: 100px; height:100px;" /></td>
			</tr>
		}
	</tbody>
</Table>

Clase3/Clase.MVC.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina Principal";
}

<div class="text-center">
    <h1 class="display-4">Bienvenidos</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Clase3/Clase.MVC.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Clase.MVC.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Clase.MVC.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clase.MVC.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animales" asp-action="">Lista de animales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animales" asp-action="Agregar">Agregar Animales</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Clase.MVC.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>